[server]
host = "127.0.0.1"
port = 8080

[database]
url = "postgres://postgres:postgres@localhost:5432/task_manager"


[cors]
allowed_origin = ["http://localhost:3000/","*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE"]