[server]
host = "0.0.0.0"
port = 8080

[database]
url = "postgres://postgres:postgres@localhost:5432/task_manager"

[cors]
allowed_origin = ["https://nosyntax.net/task-manager"] 
allowed_methods = ["GET", "POST", "PUT", "DELETE"]