version: '3.8'  

services:
  # سرویس PostgreSQL
  postgres:
    image: postgres:15-alpine  
    container_name: task_manager_db  
    environment: 
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: task_manager  
    ports:  
      - "5432:5432"  
    volumes: 
      - postgres_data:/var/lib/postgresql/data  
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]  
      interval: 5s  
      timeout: 5s 
      retries: 5  

  
  pgadmin:
    image: dpage/pgadmin4  
    container_name: task_manager_pgadmin  
    environment:  
      PGADMIN_DEFAULT_EMAIL: saza@gmail.com # ایمیل ورود
      PGADMIN_DEFAULT_PASSWORD: admin  
    ports:  
      - "5050:80" 
    depends_on:  
      - postgres 
    volumes:  
      - pgadmin_data:/var/lib/pgadmin  


volumes:
  postgres_data:
  pgadmin_data:  